### ISSUE TITLE
Add Android navigation bar

### ISSUE THREAD

**Issue by alvaromb** [APSL/react-native-navigator-wrapper#2]

**Comment by cdsap** [comment]
@alvaromb I can help, but do you have any example how to contribute applying the native view?

**Comment by alvaromb** [comment]
Hi @cdsap! 

There's no need to use a native view component, using FB's `<Navigator />` generates a native view through the js library. This is the main advantage to use the Facebook implementation of navigator, we can have almost the same codebase for navigation, but with custom components tailored for each platform.

So, what we need is to have a different [`NavBar.ios.js`](https://github.com/APSL/react-native-navigator-wrapper/blob/master/lib/NavBar.ios.js). For instance, a `NavBar.android.js` file with a custom route mapper (like [`RouteMapper.ios.js`](https://github.com/APSL/react-native-navigator-wrapper/blob/master/lib/RouteMapper.ios.js)) to match the Material design or the Android Human Interface Guidelines.

There's an official setup guide for Android development, you can find it [here](http://facebook.github.io/react-native/docs/android-setup.html#content).

Please let me know how to help you with this issue, I would really love to support Android's look and feel.

**Comment by cdsap** [comment]
Hi @alvaromb 
Sorry, I understood about the requirement of implement one native view. I don't have enough experience to apply it with React.
