### ISSUE TITLE
Work with ExNavigator

### ISSUE THREAD

**Issue by cancan101** [APSL/react-native-navigator-wrapper#5]
`ExNavigator` seems pretty popular rather than directly using `Navigator`. 
See:
- https://medium.com/the-exponent-log/routing-and-navigation-in-react-native-6b27bee39603
- https://github.com/exponentjs/ex-navigator

**Comment by alvaromb** [comment]
I'm closing the issue. There is a lot of confusion about the navigators right now, I hope we will converge to some abstraction using the `ExperimentalNavigator` soon.
