### ISSUE TITLE
Fix example code

### ISSUE THREAD

**Issue by fibbers** [APSL/react-native-navigator-wrapper#7]
Hi,

`<NavigationWrapper` in the example should be replaced with `NavigatorWrapper`. I found out by checking the source, but others might be able to get this library started quicker :)

Regards,
Willem

**Comment by alvaromb** [comment]
Thanks @fibbers!

I've updated the `README.md` file. Aside of that, expect a full revamp of the `routeMapper` stuff very soon, so feel free to open any issues if you have any idea or suggestion. I want to provide a consistent API to configure the navigation bar element.
